## ──────────────────────────────────────────────
## SecretStore: AWS Secrets Manager (us-east-1)
## Usa o Secret aws-credentials (criado pelo Terraform neste namespace).
## ──────────────────────────────────────────────
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-us-east-1
  namespace: solidarytech-donation
  labels:
    app.kubernetes.io/name: donation-service
    app.kubernetes.io/component: donation
    app.kubernetes.io/part-of: solidarytech
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-credentials
            key: session-token
